kubernetes-sigs/cluster-api-provider-kubevirt

main.go
Limit the controller to watch for cluster-api objects only in specific namespace
This is done as in our use case we need this controller watch objects only in specific namespace
=> Add namespace option to manager start

README.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #25
This PR enhances the README particularly for Kubevirt
```NONE
```
=> Improvement of Readme

README.md
This adds the meeting details to the README of the project.
Fixes #29
=> added meeting info to the README

README.md
**Added the weekly meeting schedule in the office hours section:**:
**Which issue this PR fixes** * fixes #29 
**Special notes for your reviewer**:  Please review
```release-note
```
=> Meetings Details update in README.md

.github/workflows/e2e.yaml, .github/workflows/test.yaml, README.md
Later we can decide if to publish it (e.g. to [coveralls.io](https://coveralls.io))
```release-note
None
```
=> Create coverage file on unit test in CI

controllers/kubevirtcluster_controller_test.go, controllers/kubevirtmachine_controller_test.go
Add unit test for kubevirtcluster_controller.go.
=> Add unit test for Kubevirt Cluster Controller

OWNERS
Hey, I finally got my kubernetes-sig membership. I'm requesting to be added as an approver now.
```release-note
NONE
```
=> Add davidvossel to approvers list

.github/workflows/image_build.yaml
added github workflow to build and push image
```release-note
```
=> Issue 84 - created image build and push workflow

api/v1alpha1/api_suite_test.go, api/v1alpha1/kubevirtmachinetemplate_webhook_test.go, controllers/kubevirtcluster_controller_test.go, controllers/kubevirtmachine_controller_test.go, controllers/kubevirtmachine_suite_test.go, e2e-tests/create-cluster_test.go, e2e-tests/e2e_tests_suite_test.go, go.mod, go.sum, hack/build-e2e.sh, pkg/kubevirt/kubevirt_suite_test.go, pkg/kubevirt/machine_test.go, pkg/loadbalancer/loadbalancer_suite_test.go, pkg/loadbalancer/loadbalancer_test.go, pkg/ssh/cluster_node_ssh_keys_test.go, pkg/ssh/ssh_suite_test.go
Moving to ginkgo v2 allows filtering by labels. We want this feature for the e2e tests.
```release-note
None
```
=> Move to ginkgo v2

OWNERS
Add nirarg to the approvers list
=> Add nirarg to the approvers list

OWNERS
Add nunnatsa to the approvers list
```release-note
None
```
=> Add nunnatsa to the approvers list

.github/workflows/e2e.yaml
=> Add missing go compiler to the e2e test

.github/workflows/e2e.yaml
=> This PR is a hotfix for the broken CI, it fixes a typo in the e2e workflow

.github/workflows/e2e.yaml
The previous fix didn't work.
I fixed a typo, but in the place of the previous fix, the path to the file was still wrong.
Hopefully this will fix it.
```release-note
```
=> clusterkubevirtadm-fix 2

.github/workflows/e2e.yaml
Change clusterkubevirtadm to use --kubeconfig flag
=> Change clusterkubevirtadm to use --kubeconfig flag

docs/our-image-creation-process.md
=> added docs for creating the image-builder image

e2e/create-cluster_test.go
Reverts kubernetes-sigs/cluster-api-provider-kubevirt#144
=> Revert "Fix flaky e2e test"

pkg/infracluster/infracluster.go
When the end-user is requesting a tenant cluster to be created in an external infrastructure cluster, the logic that resolves the namespace where to spawn it doesn't take the namespace set for the current context in the `kubeconfig` that has been provided (please see the issue for the full resolution logic).
This change addresses this by leveraging the `clientcmd.ClientConfig`; which offers a `Namespace` method that will return the namespace of the current context, if it is set, and fallback to `"default"` otherwise.
fixes #158
This fix simply replace the direct call to `clientcmd.RESTConfigFromKubeConfig` to generate the REST config, with the intermediate call to first generate …
=> Select kubeconfig current context namespace before 'default'.

metadata.yaml
=> Updated metadata.yaml major version to 0 to fix clusterctl problem

.github/workflows/create_release.yaml
=> Add the cluster-template.yaml file to the relrase assets

pkg/ssh/cluster_node_ssh_keys.go
fixes #172 
```release-note
NONE
```
=> Fix unnecessary double write to ssh key secret

.github/OWNERS, OWNERS, e2e/OWNERS, hack/OWNERS, templates/OWNERS
Add Quique as approvers to select directories
```release-note
NONE
```
=> owners: Add Quique as owners to some sub directories

controllers/kubevirtcluster_controller.go
=> condition to use controlPlaneEndpoint values

.github/workflows/clusterkubevirtadm-test.yaml, .github/workflows/create_release.yaml, .github/workflows/image_build.yaml, .github/workflows/test.yaml
Only run github actions on the original repository
```release-note
None
```
=> Protect github actions
