.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Add .github templates to set up the standard of PRs and ISSUEs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
N/A
N/A
**Release note**:
```
N/A
```
=> Add .github templates

go.mod, go.sum, pkg/ssh/utils.go
Fixes an issue where golang ssh can't connect to some ssh servers which
do not accept ssh-rsa preauthentication and make the connetions fail
with:
```
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
```
For instance fedora can't be used in its default configuration since fc33. EC is around long enough to assume that every relevant OS can accept it. Since more and more services start to disable ssh-rsa a switch to EC seems to make sense.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #19 
```release-note
Switch SSH keys from RSA to EC and update …
```
=> Update golang.org/x/crypto and switch from RSA to EC keys

pkg/loadbalancer/loadbalancer_test.go, pkg/ssh/cluster_node_ssh_keys_test.go, pkg/ssh/ssh_suite_test.go
What this PR does / why we need it:
The initial code migration for cluster-api-provider-kubevirt by Apple Inc.
Unit tests for cluster_node_ssh_keyss.go
Which issue this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):
N/A
Special notes for your reviewer:
N/A
Release notes:
N/A
=> Add unit test for cluster_node_ssh_keys.go

Makefile, pkg/ssh/cluster_node_ssh_keys_test.go
Switching the ssh tests to `kubevirt.io/api` to make the tests compile.
The kubevirt API is now coming from `kubevirt.io/api` instead of
`kubevirt.io/client-go`.
```release-note
NONE
```
=> Fix an import error in the ssh unit tests

api/v1alpha4/kubevirtmachine_types.go, api/v1alpha4/kubevirtmachinetemplate_webhook_test.go, config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml, controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go, hack/functest.sh, pkg/context/machine_context.go, pkg/kubevirt/machine.go, pkg/kubevirt/machine_test.go, pkg/ssh/ssh_command_executor.go, pkg/testing/common.go
Fixes: #26 
This PR makes the following changes.
* Only injects ssh keys when user-data is of type cloud-init, otherwise the userdata is taken directly as is with no modification.
* Determines if a VM is booted by checking the ready condition on the VMI rather than performing ssh execution for hostname.
* Optionally determines if a VM is bootstrapped only if the VM has ssh keys injected via cloud-init userdata, otherwise bootstrap detection of the sentinel file is ignored.
* Removes the kubevirtMachine.Spec.Bootstrapped boolean in favor of using conditions on the Status struct.
The overall result here is that previous behavior using the Kubeadm bootstrap provider is largely exactly the same. The only difference is that the IsBooted() check now only checks the ready condition on the VMI …
=> Make ssh bootstrap detection optional

.github/workflows/e2e.yaml, .github/workflows/test.yaml
Add github actions for:
* running unit tests
* building the capik manager
* triggering an e2e jobs in kubevirt-prow and wait for its completion
Two points to consider:
* A KUBECONFIG secret needs to be added to github actions to make the e2e job work.
* The job right now also succeeds if the remote jobs fails, it just indicates the end of the remote job, not if it succeeded or failed.
```release-note
NONE
```
=> Add unit- and functional test runners based on github actions

.github/workflows/e2e.yaml
If a PR gets labeled with `ok-to-test` the integration test job is
triggered and this github action has access to secrets.
The github action does for security resaons not allow secrets on all
PRs, so we add this extra step.
Still, the action itself, while using a secret, does not have any
interaction points with users. The PR content is actually not even
checked out.
Also see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for more details and being able to judge for yourself if you consider this safe. …
=> Make secrets for third-party PRs available

Dockerfile, config/manager/manager.yaml
Update Dockerfile to build manager binary and emit production image. The Dockerfile is inspired from CAPI.
**Which issue this PR fixes**: fixes #45
=> Add Dockerfile to build manager binary and emit production image

controllers/kubevirtmachine_controller_test.go, pkg/kubevirt/machine.go
This PR introduces two changes.
* Adds unit tests to exercise reconcileNormal() behavior
* fixes race condition in kubevirt machine controller that causes reconcile error immediately after VM creation
I noticed quite a few `failed to create VM instance` errors in the logs and found a race condition in our VM creation logic. If we attempt to get a VM's VMI immediately after VM creation, there's a very high chance that get will fail. This is because the VM controller has not had enough time to react to the created VM and create the corresponding VMI object.
We don't actually need to check to see if the VMI has been created immediately after the VM is created. Now that the machine controller is checking the `IsReady()` function, we'll naturally wait (re-enqueue) the VMI to get recreated …
=> Fixes "failed to create VM instance" error

.github/workflows/test.yaml, kubevirtci
With the new Dockerfile in place with #46  which builds the manager binary, the
binary does not have to be built upfront with the external golang
version. Instead the internal one can be used which makes for instance
integration jobs independent of the go versions installed there.
```release-note
NONE
```
=> Make integration tests independent of go version changes

.github/workflows/e2e.yaml, .github/workflows/test.yaml
Add a condition to the github action, to prevent them to run on another repositories, like forks.
We don't want the github action to run on forks of this repository. This PR prevents that.
```release-note
None
```
=> Limit github action to run only on the kubernetes-sigs/cluster-api-provider-kubevirt repository

controllers/kubevirtmachine_controller.go, go.mod, go.sum, pkg/kubevirt/machine.go, pkg/kubevirt/machine_test.go, pkg/testing/common.go
Add unit tests for the Machine.Create function, to increase test coverage.
While working on it, changed the function a bit to use the request context, instead of `context.ToDo`
```release-note
None
```
=> Add unit tests for Machine.Create

.github/workflows/e2e.yaml
https://github.com/kubernetes/test-infra/pull/24686 landed a while ago, the new mkpj flag can be used now.
The github action will now also fail when the prowjob failed and not just indicate when the prowjob is done.
The change will only be effective after this PR with the change is merged.
```release-note
NONE
```
=> Add the new --fail-with-job flag to let mkpj fail when the prowjob fails

.github/workflows/e2e.yaml
Ensure that we react to a label change on the PR to ensure that the e2e
tests get triggered if someone writes /ok-to-test some time after the PR
got created.
`labeled` is the new event. The other three events are the default values.
Right now, if the label gets added to PRs some time later, github will not reconsider if it has to run the integration test unless the code in the PR gets repushed.
```release-note
NONE
```
=> Run e2e test also on label events

metadata.yaml
`metadata.yaml` is intended to indicate compatibility of versions between cluster-api and providers
currently, kubevirt provider metadata declares compatibility with cluster-api `v0.1.x` while it's actually compatible with cluster-api `v1.0.x`
one manifestation of this is an error below when using current version of kubevirt provider with clusterctl `v1.0.x`:
```
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha1 for provider infrastructure-kubevirt
```
after this code change, such error no longer shows, and we can successfully intialize capi management plane with capi `v1.0.x` and capk `v0.1.x`
```
Fetching providers
Installing cert-manager Version="v1.5.3"
Waiting for cert-manager …
```
=> make 0.1.x version of kubevirt provider compatible with 1.0.x version of cluster-api

templates/cluster-template-ext-infra.yaml
- use v1beta1 versions for cluster-api resources
- use v1alpha1 versions for kubevirt provider resources
```NONE
```
=> fix API versions in external infra template

api/v1alpha1/kubevirtcluster_types.go, controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go, e2e-tests/create-cluster_test.go, kubevirtci, pkg/kubevirt/machine.go, pkg/kubevirt/machine_test.go, pkg/testing/common.go, templates/cluster-template-persistent-storage.yaml, templates/cluster-template.yaml
This PR adds support for continually detecting readiness of a KubeVirtMachine after the initial bootstrapping succeeds. This is needed to properly handle detecting when a VM crashes/fails (via MachineHealthCheck) as well as updating the node IPs when a VM restarts.
During a restart, the VM's IP will change due to being hosted in a new pod. That IP must be reflected on the KubeVirtMachine object which means we need to continually reconcile the VM in order to detect when such an IP change occurs.
The KubeVirtMachine.Status.Ready boolean should continually be reconciled after the initial bootstrap completes. This ready boolean on the KubeVirtMachine status translates to the corresponding Machine's ready condition. That ready condition is one of the values commonly used by the …
=> Continually reconcile KubeVirtMachine objects

pkg/kubevirt/utils.go, pkg/loadbalancer/loadbalancer.go
This PR add another label `cluster.x-k8s.io/cluster-name` for each VM and VMI in workload cluster because existing label `cluster.x-k8s.io/role=control-plane` is not enough to identify different cluster. With existing label works with this new label, now we can identify each workload cluster master node in service selector.
This PR is resolve issue https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/74
=> fix issue #74

controllers/kubevirtcluster_controller.go
When the KubevirtCluster CR is manage by an external controller, sometimes there is an update race between capk and the external controller, where each update in one hand, triggers reconcile and update in the other hand and vice versa.
This PR changes that so in this case, the CR is filtered out from the reconciling watch, and so capk will ignore changes made by an external controller.
```release-note
```
=> Fix bug in KubevirtCluster Reconciler - endless reconcile loop with external controller

Makefile
GOPROXY variables can container `|`s. In order to properly pass GOPROXY to docker, it has to be quoted.
KubeVirt CI passes now a GORPOXY variable like this: `https://proxy.golang.org|https://goproxy.io|direct`. See https://github.com/kubevirt/project-infra/pull/1885 for more context.
=> Pass the GOPROXY variable properly to docker

.github/workflows/test.yaml, e2e-tests/create-cluster_test.go, pkg/kubevirt/machine.go, pkg/kubevirt/machine_test.go, pkg/kubevirt/utils.go, pkg/ssh/ssh_command_executor.go, pkg/ssh/utils.go
Fix all the golangci-linter warning (except for two deprecated function calls) and add the linter as a github action and a merge gate.
There are still two warning excluded from linter run, because of two deprecated function calls. see details here #85 
```release-note
None
```
=> Add go-linter to the github action

CONTRIBUTING.md, Makefile, controllers/kubevirtcluster_controller.go, controllers/kubevirtcluster_controller_test.go, controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go, controllers/kubevirtmachine_suite_test.go, e2e-tests/create-cluster_test.go, hack/tools/tools.go, main.go, pkg/context/cluster_context.go, pkg/context/machine_context.go, pkg/infracluster/infracluster.go, pkg/infracluster/mock/infracluster_generated.go, pkg/kubevirt/kubevirt_suite_test.go, pkg/kubevirt/utils.go, pkg/loadbalancer/loadbalancer.go, pkg/loadbalancer/loadbalancer_suite_test.go, pkg/loadbalancer/loadbalancer_test.go, pkg/ssh/cluster_node_ssh_keys.go, pkg/ssh/cluster_node_ssh_keys_test.go, pkg/testing/common.go, pkg/workloadcluster/mock/workloadcluster_generated.go, pkg/workloadcluster/workloadcluster.go
This PR is a result of running goimports. Many golang files are affected from that, changing their order of imports and code format.
The PR also adds the `make goimpots`, `make linter` and `make sanity`.
The last one contain the other two and also running the unit tests. 
It is expected from a PR author to run `make sanity` before pushing the PR.
```release-note
```
=> Sort the imports and reformat all golang files

controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go, e2e-tests/create-cluster_test.go, kubevirtci, pkg/kubevirt/machine.go
When a KubeVirt Cluster object is managed by an external controller (meaning not by our capk cluster controller) then the ssh keys generated by our capk cluster controller in order to introspect VM guests will not be present. The machine controller needs to know and expect that these ssh keys won't be available when the cluster is externaly managed and still process the VM.
This PR also addresses timing issues with how a worker node's provider ID doesn't always get set in certain situations when external clusters are in use.
In addition to the logical fixes, unit tests and e2e functional tests have been added to exercise the external cluster behavior. I had to add a new workaround for our e2e test suite setup that sources cert-manager from the new cert-manager repo. This addressed a new …
=> Do not wait for SSH keys if there is an external controller

templates/cluster-template-ext-infra.yaml, templates/cluster-template-persistent-storage.yaml, templates/cluster-template.yaml
Template doesn't have service configuration today, since clusterapi already has this supported, this PR add service cidr configuration in template file, so user can customize service cidr if they want.
=> add serivce cidr configuration in template

controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go
fixes #98 
If a cluster is created and immediately destroyed before the bootstrap secret is created, it was possible to segfault during machine teardown.
```release-note
Fixes segfault when during cleanup when bootstrap secret is not present on a machine
```
=> Fixes KubeVirtMachine segfault during tear down

.github/workflows/test.yaml, controllers/kubevirtmachine_controller_test.go
the "should ensure deletion of KubevirtMachine when bootstrap secret was never created" unit test is failed to be compiled.
This PR fixes the mock expect call, so now the test is compiled, run and passed
```release-note
None
```
=> Fix a unit test

controllers/kubevirtcluster_controller.go, pkg/loadbalancer/loadbalancer.go
Return external IP if LoadBalancer type service enabled for API endpoint.
Also add 10 seconds delay for loadbalancer to assign external IP after LB created, otherwise, may return ClusterIP incorrectly.
=> returen external IP address for loadbalancer

.github/workflows/e2e.yaml
Fix clusterkubevirtadm-linux-amd64 calling from e2e cluster creation workflow
=> Fix clusterkubevirtadm-linux-amd64 calling from e2e cluster creation workflow

.github/workflows/e2e.yaml
This is not working for now, and fails the E2E test lane.
```release-note
None
```
=> Restore the E2E test to not use clusterkubevirtadm

clusterkubevirtadm/cmd/credentials/credentials.go, clusterkubevirtadm/cmd/credentials/credentials_test.go
The capk user need also permissions for the following resources
In order to create the tenant cluster
* virtualmachineinstances
* secrets
* services
=> Add More permissions to clusterkubevirtadm Role

e2e-tests/create-cluster_test.go, kubevirtci, templates/cluster-template-persistent-storage.yaml
This PR exposes storage class and volume size as tunables for the persistent storage template. It also transitions us to using rook-ceph for kubevirt ci storage.
We needed to switch to rook-ceph because we hit some limitations with how big of a volume we could provision using local storage. This resolves those limitations which will allow us to use the new image builder images @isaacdorfman  is working on in PR #108 
```release-note
NONE
```
=> Switch to using rook-ceph for e2e storage class

kubevirtci
This commit changes kubevirtci to behave like the tenant cluster is created on ext infra
This is done in order to test the cluster creation with clusterkubevirtadm limited kubeconfig
This will also allow us to follow another resources would be added in the future to the tenant cluster creation
Notice: added special behavior for kubevirtci, in which the "localhost" IP in the kubeconfig is replaced
with the controlplane VM IP, in order to allow using the kubeconfig inside the cluster
=> Change "kubevirtci create-cluster" command to use clusterkubevirtadm kubeconfig

Makefile, e2e/create-cluster_test.go, hack/functest.sh, kubevirtci
I created a kubevirt target in my fork of the image-builder project:
https://github.com/isaacdorfman/image-builder/tree/kubevirt-target
This image is the image of the machines in the cluster.
I pushed the image I built in my image-builder fork into quay and updated the capk to use this image instead of the kubevirtci one.
In this PR I also fixed the problems that this change caused.
*I also fixed a problem with the local container reigstry by changing the url of the registry from localhost to 127.0.0.1, this caused problems related to ipv6 in some devices. …
=> Added integration with the image-builder kubevirt image

e2e/common_test.go
In order to debug e2e test failures, add failure printout to the `RunCmd`
function, so we could understand what went wrong in case of a failure.
-->
```release-note
None
```
=> Add failure printout to the e2e test RunCmd function

kubevirtci
This PR add option to access tenant cluster created on kubevirtci infra cluster, using virtctl port-forward
Also added better usage display, can be printed by calling `./kubevirtci help`
=> kubevirtci: Add option to interact with the tenant cluster and improve usage (help)

kubevirtci
This updates the kubevirtci script to include the following changes
- adds ssh commands for accessing tenant and infra nodes
- adds a destroy-cluster command
- separates create-cluster into two commands, create-cluster and create-external-cluster. The new create-external-cluster command simulates an external cluster using the clusterkubevirtadm command. The normal create-cluster commands treats the infra and management as the same cluster.
- adds the namespace to the create-cluster command so clusters are created in the $TENANT_CLUSTER_NAMESPACE instead of the default namespace.
- fixes the new `kubectl-tenant` command to look in the $TENANT_CLUSTER_NAMESPACE when finding the guest cluster's kubeconfig
```release-note
NONE
```
=> Kubevirtci updates

kubevirtci
This PR adds two new commands
```./kubevirtci install-metallb``` which installs and configures a metallb instance in the kubevirtci cluster
```./kubevirtci curl-lb <lb name> <lb namespace>``` Which curls the load balancer services external ip and port then dumps the log output to stdout.
```./kubevirtci install-capk``` which installs capk from the release manifests instead of source. This allows the kubevirtci script to be used outside of the capk source tree (like in cloud-provider-kubevirt or kubevirt csi)
```./kubevirtci clean-cache``` which cleans the local clusterctl, virtctl, and tmp files used by kubevirtci
Install metal lb
```
./kubevirtci install-metallb
```
Post these pods and LB service to the infra cluster
```
kind: Pod
apiVersion: v1
metadata:
name: foo-app
labels:
app: …
```
=> Kubevirtci metal lb support

e2e/common_test.go, e2e/create-cluster_test.go, kubevirtci, templates/cluster-template-ext-infra.yaml, templates/cluster-template-persistent-storage.yaml, templates/cluster-template.yaml
Fixes: #76
Previously, our clusterctl templates for guest clusters conflicted with any underlying infra cluster setup with the default kubeadm settings. This meant that if someone setup their infra cluster using the kubeadm default settings, then used capk to install guest clusters, that the guest cluster's cidr ranges and dns would overlap with the infra cluster. The result is that the guest cluster never reached a fully healthy state where cni would work successfully.
This pr adds the following fixes.
* All the templates are updated to offset the guest cluster network cidr ranges from the default kubeadm cidr ranges
* kubevirtci now has the `./kubevirtci install-calico` command for installing cni into guest clusters
* The e2e tests now install calico and validate both guest cluster node …
=> Network fixes

pkg/kubevirt/machine.go, pkg/kubevirt/machine_test.go, pkg/testing/common.go
**What this PR does / why we need it**: 
This PR fixes the deletion of a tenant-cluster spawned in an external infrastructure cluster. Before this change, unless the tenant cluster was in the namespace with the same name than the namespace where its specification has been created in the management cluster, then the logic that looks for the VMs will not find them and not delete them.
**Which issue this PR fixes**: fixes #150
Please note that this PR contains two commits to help with the review:
1. The first commit includes only changes to `pkg/kubevirt/machine_test.go` to allow specifying a different namespace and to add missing tests of the deletion when the tenant-cluster is spawned internally in the management cluster.
2. The second commit includes …
=> Fix external deletion

controllers/kubevirtcluster_controller.go, controllers/kubevirtcluster_controller_test.go, controllers/kubevirtmachine_controller.go
When reconciling for deletion, the KubevirtCluster and KubevirtMachine controllers both attempt to patch, as the last step of the reconciliation, the resource in order to indicate to the user that it is being deleted. It is possible that, by the time these patches are called, the resource is already deleted; which result of the patch failing with a `NotFound` error that is then reported at the error level in the log.
Because this is an expected case, this change silences `NotFound` errors raised by these two final patches. 
**Which issue this PR fixes**:
fixes #152
Note that the patch methods return an `k8s.io/apimachinery/pkg/util/errors#Aggregate` error in this case; which will not be recognized by the …
=> Avoid reporting not-found errors when patching resources under deletion.

kubevirtci
Some guards are missing from kubevirtci script, this change add them:
- Wait for cluster readiness after creation
- Wait for vms readiness
- Wait for calico node pod readiness
- Wait for tenant node readiness
Copied from https://github.com/kubevirt/cloud-provider-kubevirt/pull/113
It may help with e2e flakiness
```release-note
NONE
```
=> kubevirtci: Wait for cluster and calico

controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go
Cluster-API's Kubeadm bootstrap provider exposes the capability to end-user to specify users to add to control or compute plane nodes. When a end-user does so, then the corresponding `users` section is generated in the cloud-init bootstrap data. This section conflicts with the one that is currently added by the Kubevirt provider to add the `capk` user that is used to check each node health.
This PR address this conflict by:
* adding the `capk` user to the users section if one exists already
* if a `capk` user exists already in this list of users, then, the former is overridden instead
* if there are not `users` section in the current cloud-init bootstrap userdata, then add the section with the `capk` user 
fixes #149 …
=> Add capk user properly when users already defined.

controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go
This ensures that the `...-userdata` secret CAPK creates to enhance the cloud-init user data generated by Kubeadm has the same label(s) that the latter.
Currently, this results in these secrets getting the `cluster.x-k8s.io/cluster-name=<cluster-name>` label.
fixes #161
```release-note
NONE
```
=> Copy Kubeadm userdata secret labels to CAPK secret.

controllers/kubevirtcluster_controller_test.go, controllers/kubevirtmachine_controller_test.go, pkg/infracluster/infracluster.go, pkg/infracluster/infracluster_test.go, pkg/infracluster/kubevirt_suite_test.go, pkg/kubevirt/machine_test.go, pkg/loadbalancer/loadbalancer_test.go, pkg/ssh/cluster_node_ssh_keys_test.go, pkg/testing/common.go
This change fixes where the `GenerateInfraClusterClient` function looks up for the infrastructure secret referenced in a `KubevirtCluster` or `KubevirtMachine`, when no namespace is specified in the `ObjectReference`.
This corrects the current logic by ensuring that, in this case, the code looks for the secret in the same namespace than the referencing resource; which aligns with the default behavior that CAPI follows for other `ObjectReference`s.
To validate this change of behavior, this PR also introduce a set of tests for the `infracluster` package.
fixes #165
Note that this change is split in two commits:
* The first one with a refactoring that extract the duplicated …
=> Fix infra secret lookup so that it defaults to the namespace of the referencing resource

e2e/e2e-suite_test.go, hack/run-e2e.sh
The kubevirt project has a cmd to dump artifacts with the k8s reporter.
This changes creates a similar dump command integrated with the capk
deps, It will dump stuff at JustAfterEach it test fails.
The artifacts are stored by [file-name]:[line-number] like at following run:
https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubernetes-sigs_cluster-api-provider-kubevirt/156/pull-kubernetes-sigs-cluster-api-provider-kubevirt-e2e/1551839261811019776/artifacts/
```release-note
NONE
```
=> test, reporter: Integrate with kubevirt dump

Makefile, hack/conformance.sh, hack/run-conformance.sh
This PR introduces conobuoy conformance test script.
[Fist commit](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/commit/23f5209983de51b6c03ead87d865841337158237):
- adds hack scripts that download and execute default sonobuoy conformance suite in tenant cluster.
[Second commit:](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/commit/b3d4d58691c22127c857ad34e68f92b8ea4b6d05)
- updates current ssh-infrra function to accept optional commands to run on the infra node, without getting interactive shell.
a consequence of this change is that namespace (second parameter) is required.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR …
=> e2e: sonobuoy conformance tests

.github/workflows/create_release.yaml, .github/workflows/image_build.yaml
Build and push multi-arch images + manifest in github actions
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #142 
```
❯ curl -L https://github.com/jbpratt/cluster-api-provider-kubevirt/releases/download/v0.1.2-test-3/infrastructure-components.yaml | kubectl apply -f -
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  630k  100  630k    0     0   131k      0  0:00:04  0:00:04 --:--:--     0
namespace/capk-system created
customresourcedefinition.apiextensions.k8s.io/kubevirtclusters.infrast …
```
=> build and publish multi-arch image manifest

hack/run-e2e.sh
The variable used to pass the kubevirt version to the dump URL was wrong, this change fix that.
```release-note
NONE
```
=> tests, artifacts: Fix the version to dl kv dump

Makefile, config/kccm/kustomization.yaml, config/rbac/role.yaml, controllers/kubevirtcluster_controller.go, hack/kccm-flavor-gen.sh, kubevirtci, pkg/testing/common.go, templates/cluster-template-kccm.yaml, templates/cluster-template-persistent-storage-kccm.yaml
The clusterctl tool has a "--flavor" using this a cluster with
cloud-provider-kubevirt integrated can be created doing:
cluterctl generate cluster --infrastructure kubevirt --flavor kccm
This change create at tool to generate those flavors from a
cloud-provider-kubevirt repository.
TODO:
```release-note
Add kccm flavors for clusterctl 
```
=> template: Add kccm flavor

kubevirtci
The ubuntu image was missing the console kernel params to be able to use virtctl console with it. This change use image-builder [1] to create a k8s-1.23.10 ubuntu image with console activated.
[1] https://github.com/kubernetes-sigs/image-builder/pull/984
```release-note
NONE
```
=> kubevirtci: Update guest image to have console

.gitignore, kubevirtci
Everytime kubevirtci is call a fetch is run this is totally unnecesary and somtimes it fails, this change refactor the fetch to do it when necessary and also move the kubevirtci cloned path to .kubevirtci.
```release-note
NONE
```
=> kubevirtci: Refactor fetch mechanism

.github/workflows/create_release.yaml, templates/cluster-template-lb.yaml
Add new template file: `cluster-template-lb.yaml`. Also add it to the release.
This file is identical to the `cluster-template.yaml` file, except for the service type, that changed to `LoadBalancer`.
```release-note
None
```
=> Add and release cluster-template-lb.yaml

Dockerfile, Makefile, hack/functest.sh, kubevirtci, templates/cluster-template-ext-infra.yaml, templates/cluster-template-kccm.yaml, templates/cluster-template-lb.yaml, templates/cluster-template-persistent-storage-kccm.yaml, templates/cluster-template-persistent-storage.yaml, templates/cluster-template.yaml
cluster-api project wants to stop using the k8s.gcr.io repository, as it's too expensive. After checking in other cluster API project, it seems that this value is no longer in the template.
This PR removes all the usage in IMAGE_REPO variable; for that, the PR also upgrade the clusterctl in the kubevirtci script, to v1.2.4
```release-note
None
```
=> Remove the IMAGE_REPO env var from all the temlates

kubevirtci
Signed-off-by: Brian Carey <bcarey@redhat.com>
These changes are required to run the e2e test job under podman. Kubevirt CI has been working on moving all jobs to run under podman and the old docker in docker setup will no longer be supported. 
Add the insecure kubevirtci registry to registries.conf when using podman to push images to the registry. Currently this fails in CI as podman is unable to push to insecure registries by default. 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubernetes-sigs_cluster-api-provider-kubevirt/207/pull-kubernetes-sigs-cluster-api-provider-kubevirt-e2e/1592063138562314240#1:build-log.txt%3A510
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
=> Allow podman to push images to insecure kubevirtci registry

.github/workflows/create_release.yaml, Makefile, hack/kccm-flavor-gen.sh, templates/cluster-template-lb-kccm.yaml
There were missing template flavors at the github release used when a user generate a cluster with --infrastructure kubevirt, this change add all of the flavors and also check that the kccm ones are generated.
The github action has being refactored for simplicity
```release-note
Add all the cluster flavors
```
=> release: Add all the cluster template flavors

templates/cluster-template-ext-infra.yaml, templates/cluster-template-kccm.yaml, templates/cluster-template-lb-kccm.yaml, templates/cluster-template-lb.yaml, templates/cluster-template-persistent-storage-kccm.yaml, templates/cluster-template-persistent-storage.yaml, templates/cluster-template.yaml
This change the templates VM to be with to improve performance by using net multiqueue [1] .
[1] https://www.linux-kvm.org/page/Multiqueue#Multiqueue_virtio-net
```release-note
Activate network multiqueue at cluster templates.
```
=> templates: Activate net multiqueue

e2e/create-cluster_test.go, kubevirtci, templates/cluster-template-passt-kccm.yaml
This PR adds template with VMs using Passt binding to pod network.
Passt featureGate is enabled in kubevirtci script and Passt recommended node configuration is performed on cluster-up.
NOTE: There is a commit bumping kubevirt to 0.59.0-alpha, because while https://github.com/kubevirt/kubevirt/pull/8578 is merged in kubevirt release-0.58 branch, [the change hasn't made it to v0.58.0 tag](https://github.com/kubevirt/kubevirt/blob/v0.58.0/pkg/network/infraconfigurators/passt.go).
Lastly, an e2e test is added to exercise cluster creation with Passt binding. …
=> Introduce cluster template with Passt binding 

.github/workflows/create_release.yaml
Remove non-exist file from the release asset list.
```release-note
None
```
=> Fix the release automation

controllers/kubevirtmachine_controller.go, main.go
Issue #100 and #78 have two things in common, they both involve issues derived from tracking VM/VMIs on external infra.
So far, we've been treating external infra as an advanced usecase, and not the default use case. The result is that external infra has been treated as a second class citizen to the use case where the capi components and VM/VMIs are running on the same k8s cluster.
I'd like to return to a single code path that satisfies the use case where the capk/capi components are running on the same cluster as the VM/VMIs (centralized infra use case) and the use case where the controller components run on a separate cluster from the VM/VMIs (external infra use case)
To achieve this, we can't assume that the VM/VMI objects are even registered on the same cluster as the capi/capk …
=> Remove vmi/vm watch and reduce default sync time to 90 seconds

Makefile
Problem: Previously all of Kubernetes' image hosting has been out of gcr.io. There were significant egress costs associated with this when images were pulled from entities outside gcp. Refer to https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
Solution: As highlighted at KubeCon NA 2022 k8s infra SIG update, the replacement for k8s.gcr.io which is registry.k8s.io is now ready for mainstream use and the old k8s.gcr.io has been formally deprecated and projects are requested to migrate off it. This commit migrates remaining references for kubernetes-sigs/cluster-api-provider-kubevirt to registry.k8s.io.
I have verified that `registry.k8s.io/kustomize/kustomize:v3.8.7` exists …
=> Replace deprecated k8s registry references

templates/cluster-template-kccm.yaml, templates/cluster-template-lb-kccm.yaml, templates/cluster-template-passt-kccm.yaml, templates/cluster-template-persistent-storage-kccm.yaml
**What this PR does / why we need it**: The templates provided have some caveats regarding cluster name and namespace.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A
**Special notes for your reviewer**: I was trying those templates and took a time to figure out the substitutions I had to perform here.
=> Fix namespace/cluster name on templates.

docs/faq.md
As documentation is still in very initial phase, I thought it would be nice to have a little FAQ for main questions I've got around the tool when testing it myself.
Thanks
**What this PR does / why we need it**: This just adds a simple FAQ document, so that the project can add documentation in an easy way while the official documentation is not ready.
=> Frequently Asked Questions

api/v1alpha1/kubevirtcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
It sets a default value for the `KubeVirtCluster.status.ready` field, suppressing the annoying values when updating for the first time `KubeVirtCluster`.
**Which issue this PR fixes**:
fixes #252 
Although this changes the specification, thus requiring a minor bump, the API change is absolutely minimal and could be considered a patch one.
```release-note
NONE
```
=> fix(api): default value for KubeVirtCluster.status.ready field

controllers/kubevirtcluster_controller.go, main.go
Cache lazy loading is disabled when the API Reader client is getting or listing objects, as the opposite with the manager client.
**Which issue this PR fixes**:
fixes #254
```release-note
NONE
```
=> fix: api reader for CCM clean-up to avoid cache lazy loading

controllers/kubevirtcluster_controller_test.go, hack/kccm-flavor-gen.sh
This unit test is broken. This PR fixes it by populating the `KubevirtClusterReconciler.APIReader` field in unit-test, for mocking.
In addition, this PR also fixes the `hack/kccm-flavor-gen.sh` script so it will
replace the hard coded names with the right variables.
fixes #258 
```release-note
None
```
=> Fix "should succeed with the kubevirt cluster being deleted" unit test

.github/workflows/clusterkubevirtadm-test.yaml, .github/workflows/create_release.yaml, .github/workflows/e2e.yaml, .github/workflows/image_build.yaml, .github/workflows/test.yaml, Dockerfile, Makefile, go.mod
=> Bump golang to 1.20

.github/workflows/test.yaml, .golangci.yml, Makefile
Currently, there's no version pinning for the `golangci-lint` utility used, I had to manually retrieve it.
Rather, having it declared, makes it easy for contributors to linting the code.
A local binary will be stored in the `./bin` folder to avoid collision with global installed Go modules.
Untracked
```release-note
NONE
```
=> chore(golangci-lint): v1.54.2 pinning and config file

.github/workflows/pr-gh-workflow-approve.yaml
Github actions are not running for non-member contributors, unless a repo admin presses the "Approve and Run" button. The problem with that is that PRs are getting merged with no verification, causing leak of bugs into the codebase.
This PR copies a github action from the cluster-api repo, that approve running the github action by adding the `ok-to-test` label.
Source: https://github.com/kubernetes-sigs/cluster-api/blob/613a37e0183e818403ff086165bd619393b34178/.github/workflows/pr-gh-workflow-approve.yaml
```release-note
None
```
=> Allow runing github action with `ok-to-test`

controllers/kubevirtmachine_controller.go
We've seen instances where the vmi.Status.Interfaces list temporarily clears and stops reporting the default instance IP. This occurs when the qemu guest agent can not be contacted, such as during an internal soft reboot. It also occurs for reasons we do not 100% understand yet.
Since we know this vmi.Status.Interfaces field is dependent on the qemu guest agent, there will be times where the agent is unavailable. To smooth over those time periods, capk now only reports IP changes on the node when we're certain the IP has actually changed, and does not clear out the internal IP when no default ip is reported on the vmi status.
```release-note
NONE
```
=> Don't mark machine ready=false when internalIP is known

config/kccm/kustomization.yaml, templates/cluster-template-kccm.yaml, templates/cluster-template-lb-kccm.yaml, templates/cluster-template-persistent-storage-kccm.yaml
The latest kccm fails if there are no IPs at LB services after some time, this change bump to it and configure the new timeout value.
```release-note
Bump kccm to v0.5.1 it will fail if there is no IPs at LB services after some time.
```
=> kccm: Bump to v0.5.1

api/v1alpha1/condition_consts.go, controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go
Currently, today if the VM creation fails for any reason, that is not directly reported on the KubeVirtMachine object which means visibility into the failure is not reported to the capi ecosystem.
This adds a condition to the KubeVirtMachine when creation fails so the capi ecosystem can report that failure and bubble it up to the various machine controllers.
```release-note
Adds condition to KubeVirtMachine when VM creation Fails
```
=> Add condition to KubeVirtMachine when VM Creation Fails

.github/workflows/test.yaml, api/v1alpha1/kubevirtmachine_types.go, clusterkubevirtadm/cmd/credentials/credentials.go, clusterkubevirtadm/cmd/credentials/credentials_test.go, config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml, config/rbac/role.yaml, controllers/kubevirtmachine_controller.go, main.go, pkg/kubevirt/machine.go, pkg/kubevirt/machine_factory.go, pkg/kubevirt/machine_test.go, pkg/kubevirt/mock/machine_factory_generated.go, pkg/testing/common.go
Be more verbose when VM is not scheduled. Add meaningful reasons and messages to the KubeVirtMachine conditions, to be reflected in the Cluster resources.
Also, make the `KubeVirtMachine.status.ready` field to be printed also if it `false`, and adding it as a new printed column named "Rwady".
=> Reflect the VM statuses to the KubeVirtCluster status

config/manager/manager.yaml
This change ensures the manager deployment meets restricted pod security
standards.
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/274
=> fix: remove hostpath volume and privileged context

pkg/context/machine_context.go
Cluster-API takes the reason and the message from the infra-machine (in our case, the KubeVirtMachine) `Ready` condition, into the cluster-api `Machine`'s `InfrastructureReady` condition. Currently the text is something like `"0 of 2 completed"`. This is not very informative.
This PR changes the behavior so now the KV Machine Ready condition will include both the reason and the message from the failed condition.
That way, the cluster-api `InfrastructureReady` condition, will also contain the same reason and message. This will make the actual issue, if exists, to more accessible to the user.
```release-note
Remove the setup counter from the KV-Machine ready status
```
=> Remove the setup counter from the KVMachine ready status

kubevirtci
In tests, bump kubevirtci's k8s to 1.30; bump the container image to k8s 1.30.1
```release-note
None
```
=> e2e: Bump to K8s 1.30

kubevirtci
=> bump metallb to v0.14.5

Dockerfile, api/v1alpha1/condition_consts.go, api/v1alpha1/kubevirtclustertemplate_types.go, clusterkubevirtadm/cmd/credentials/credentials_test.go, controllers/kubevirtmachine_controller.go, controllers/kubevirtmachine_controller_test.go, pkg/kubevirt/machine.go, pkg/kubevirt/machine_factory.go, pkg/kubevirt/mock/machine_factory_generated.go, pkg/workloadcluster/mock/workloadcluster_generated.go
Virtual Machines serving as guest cluster nodes can be live migrated, this is beneficial in case of infra cluster nodes maintainance or mulfunction,
requiring the Virtual Machines to be migrated to another node.
This PR introduces the "VMLiveMigratable" condition to KubevirtMachine, and it takes that value as-is from the underlying VirtualMachine instance.
Then, consumers of cluster-api-provider-kubevirt could make use of it and buble that information up to the end user.
```release-note
add VMLiveMigratable Condition to KubevirtMachine …
```
=> Add VM LiveMigratable Condition to KubevirtMachine

api/v1alpha1/kubevirtclustertemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclustertemplates.yaml
The current CRD does not allow modification of any field in KubevirtClusterTemplate resources. That prevent user to add annotations or labels to the templates, and that does not follow the regular behavior of K8s.
In addition, the new capi is trying to annotate templates, and failed to do that, and this is an actual bug.
This PR fixes the issue by making only the `Spec` field as read only, letting modifying the metadata fields as in any K8s resource.
Fixes #294 
```release-note
Allow annotate and label KubevirtClusterTemplate resources
```
=> Allow annotate and label KubevirtClusterTemplates

tilt-provider.json
This adds a `tilt-provider.json` file to make it easier to use Tilt with the provider using the instructions from the [upstream CAPI docs](https://cluster-api.sigs.k8s.io/developer/tilt). 
To test, I used a tilt-settings.json file like this:
```json
{
"enable_providers": [
"kubeadm-bootstrap",
"kubeadm-control-plane",
"kubevirt"
],
"default_registry": "gcr.io/richardcase",
"provider_repos": [
"/home/richard/code/oss/cluster-api-provider-kubevirt"
],
"kustomize_substitutions": {
"CLUSTER_TOPOLOGY": "true",
"EXP_CLUSTER_RESOURCE_SET": "true",
"EXP_MACHINE_POOL": "true"
},
"debug": {
"kubevirt": {
"continue": true,
"port": 30000
}
}
}
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
=> chore: add tilt provider file

templates/cluster-template-lb-flatcar-kccm.yaml, templates/cluster-template-lb-flatcar.yaml
**What this PR does / why we need it**: This PR updates the Flatcar template added in https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/300 to use containerDisks instead of PVCs as well as allow SSH-ing into nodes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #311 
**Special notes for your reviewer**: None
```release-note
Add cluster template for workload clusters running Flatcar Container Linux
```
=> Update Flatcar template

go.mod
This will allow compiling in systems with older build images.
```release-note
None
```
=> set go version to lower be generic v1.24, instead of specific v1.24.7
